sonar.organization=joshiel123
sonar.projectKey=joshiel123_UCV-SI-lab12
sonar.projectName=UCV-SI-lab12

# Rutas de código y pruebas
sonar.sources=src
sonar.tests=tests

# Ubicación del reporte de cobertura que generamos en el pipeline
sonar.python.coverage.reportPaths=coverage.xml

# Codificación
sonar.sourceEncoding=UTF-8